# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 星空
email: 370972713@qq.com
description: > # this means to ignore newlines until "baseurl:"
    不喜亦不惧，无复独多虑
    <p>处处留心皆学问</P>
    学习越超前越好

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://morgan-leon.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  morgan-leon

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/rick-kim/30/aa7/a70
  - title: github
    url: http://morgan-leon.github.io/
  - title: envelope
    url: mailto:kim.rick@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Waterloo St.
  - line: Kitchener, ON N2H3V5


# Build settings
markdown: kramdown
permalink: pretty
